### PR TITLE
Add support for Llama2, Palm, Cohere, Anthropic, Replicate, Azure Models - using litellm

### PR DESCRIPTION
**Pull request by ishaan-jaff**
This PR adds support for 50+ models with a standard I/O interface using: https://github.com/BerriAI/litellm/

`ChatLiteLLM()` is integrated into langchain and allows you to call all models using the `ChatOpenAI` I/O interface 
https://python.langchain.com/docs/integrations/chat/litellm

Here's an example of how to use ChatLiteLLM()
```python
ChatLiteLLM(model="gpt-3.5-turbo")
ChatLiteLLM(model="claude-2", temperature=0.3)
ChatLiteLLM(model="command-nightly")
ChatLiteLLM(model="replicate/llama-2-70b-chat:2c1608e18606fad2812020dc541930f2d0495ce32eee50074220b87300bc16e1")

```

### CODE REVIEW

**Comment by ishaan-jaff** [comment]
Addressing: https://github.com/fynnfluegge/doc-comments.ai/issues/9

**Comment by ishaan-jaff** [comment]
@fynnfluegge can you please take a look at this PR when possible? 

Happy to add docs/testing if this initial commit looks good to you 

If this PR looks useful would love to meet to discuss how we can be helpful to you. Here's my [calendly](https://calendly.com/d/4mp-gd3-k5k/litellm-1-1-onboarding-chat?month=2023-09) for your convenience

**Comment by fynnfluegge** [comment]
@ishaan-jaff this is great, thanks a lot! 🔥
I think a new `argarse` argument would make sense here, instead the `--gpt4` argument. Maybe `--model` with default `gpt3.5-turbo` as currently. Then any `litellm` supported model can be used with that argument. Maybe a section in the `README.md` would be helpful. 

One question: `litellm` uses only environment parameters to access sagemaker or azure hosted models right?
I also prepared a small PR that exposes the sagemaker and azure langchain api here #12 but I guess this one is absolete if we use `litellm`, isn't it?

**Comment by fynnfluegge** [comment]
@ishaan-jaff  tested with OpenAI, works great! If you could run `poetry lock` in your branch I will merge this 🙌

**Review by fynnfluegge — APPROVED** [review]

**Pull request merged**
